# Generated by Django 5.1.15 on 2026-03-13 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cash', '0001_initial'),
        ('core', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashentry',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_entries', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_registers', to='core.branch'),
        ),
        migrations.AddField(
            model_name='cashsession',
            name='cash_register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='cash.cashregister'),
        ),
    ]
