# Generated by Django 5.1.15 on 2026-03-13 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cash', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashsession',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_cash_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashsession',
            name='opened_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_cash_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashentry',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='cash.cashsession'),
        ),
        migrations.AlterUniqueTogether(
            name='cashregister',
            unique_together={('branch', 'code')},
        ),
    ]
